### ISSUE TITLE
Abstract Method Error:  Applied Energistics & MyTown

### ISSUE THREAD

**Issue by Zalidar** [MyEssentials/MyTown#12]
Having server crash when right clicking on Applied Energistics Drive.  Was repeatable with multiple drives, multiple orientations, both claimed and wilderness land.  If this has been brought to your attention please disregard.  If this turns out to be an AE issue let me know I'll I address it there.  Thanks

Zalidar

Minecraft Server 1.6.2
MyTown 1.6.1.8
AE: rv13b

Crash Report:
http://pastebin.com/Kd3H4bez

Server Log snip:
http://pastebin.com/ugVuHbXJ

**Comment by Torins** [comment]
I expect this to be a MyTown issue.

I've neglected the 1.6.2 version of mytown, seeing I myself don't use it yet.
Gonna try to prepare a 1.6.2 dev environment over the weekend and try to fix it.

This issue has been posted a few times in the minecraftforum.net topic (http://www.minecraftforum.net/topic/1889473-legobear154s-mods), but noone posted it on github yet, so thanks :)

**Comment by Zalidar** [comment]
No problem, I've seen it on the forum, but know that it's easy to get lost in that shuffle,  I'm happy to try out anything on our dev server if needed.

**Comment by Zalidar** [comment]
Just heard from AlgorithmX2 on this error, his response if it helps track it:

I looked at this method, and that method should indeed be implemented, seems like a obfuscation issue or something, maybe the version of forge or maybe mytown isn't using srg names?

Not sure, its pretty strange.

**Comment by Torins** [comment]
I've discussed the problem with Algorithm, and it was an issue with reobfuscation not obfuscating a method in AE's code.
Try using rv13.c dev3, it should work properly now.
http://ae-mod.info/Dev/

EDIT: Confirmed. I could open am ME Drive without crashing.

**Comment by Zalidar** [comment]
Indeed this seems to work without issue, thanks for the quick response and fixes.

-Zal
