### ISSUE TITLE
problems with /ta delete

### ISSUE THREAD

**Issue by trentech** [MyEssentials/MyTown#16]
Hey lego. Updated my dev server to the latest MyTown last night. Noticed today /ta delete [town] doesn't immidiately work anymore. have to /ta reload for the changes to take effect. This occurs with MySQL and SQLite

Also important note, my initial thought was it was related to my plugin as it was reported to me a week or 2 ago but it also occurs for me without my plugin installed.

**Comment by jgoett154** [comment]
I will look into it in the morning, was just about to go to sleep. I don't think anything changed to cause it, but Torins did change quite a bit when it came to how Towns where stored in the mod. This is the line for /ta delete [town] https://github.com/legobear154/MyTown/blob/master/src/ee/lutsu/alpha/mc/mytown/commands/CmdMyTownAdmin.java#L131

It has to be something in there, or the t.delete() near the bottom of the command.

**Comment by trentech** [comment]
Just found out this happens with /t delete as well

**Comment by jgoett154** [comment]
Defiantly sounds like t.delete() is not updating something properly. Torins changed the way towns where stored to ArrayList if I remember right. Might have something to do with that. Does it update the database before you run the /ta reload command?

**Comment by trentech** [comment]
Yeah the database updates, the changes just don't take affect server side
