### ISSUE TITLE
[Task] Economy Support via Vault

### ISSUE THREAD

**Issue by Slind14** [MyEssentials/MyTown#17]
Hey,

you already build a bridge for permissions via. Vault, why not for economy ?

**Comment by jgoett154** [comment]
I have actually been working on that recently, so its coming I promise :)

**Comment by Slind14** [comment]
Nice. I just found this: http://dev.bukkit.org/bukkit-plugins/mytownecon/ did you know it ?

@legobear154 do you have an irc where you hang out ?

**Comment by jgoett154** [comment]
Yes I did, I am in constant communication with the author of it and his plugin will be the primary economy plugin for ForgePerma and MyTown. :) There is going to be support for both item and curremcy based economies once I finish this update and his plugin adds a tax system which should make everyone that likes tax systems happy.
