### ISSUE TITLE
[Task] Crumble Horn & MineFactoryReloaded

### ISSUE THREAD

**Issue by Slind14** [MyEssentials/MyTown#19]
Hey,

would it be much effort to add grief prevention for the Crumble Horn and MineFactoryReloaded (Harvester, Blockbreaker)?

**Comment by jgoett154** [comment]
I started to do the crumble horn, I will have to look at the other two and see if I can.

**Comment by Slind14** [comment]
Will there be an update for 1.5.2 or only 1.6.x ?

**Comment by jgoett154** [comment]
I will update both since I know there are few modpacks for 1.6.x and most are still on 1.5.x.

**Comment by Slind14** [comment]
nice, thank you. Do you have a irc chennal where you chill out ?

**Comment by jgoett154** [comment]
I do not, but have heard there is a espert.net channel for mytown. I may get and IRC channel because it would be a nice place for people to get ahold of me easier than github, email, or mcforum.

**Comment by Slind14** [comment]
you should. register your self an acc on the espernet irc. as irc client I would recomend you: http://www.ntalk.de/Nettalk/en/

**Comment by jgoett154** [comment]
Already working on it. I am at school at the moment on my tablet. I prefer Pidgin for irc and such myself.

**Comment by Slind14** [comment]
looks childish for me, but the gui doesn´t say whats behind it.

One question to modify world, and sry if I miss use your BugTracker:

Why should I use Modifyworld2 for Forge and not for Bukkit ? Or should I use both ?

**Comment by jgoett154** [comment]
I find pidgin to be powerful, plus you can customize the look with themes and there are plugins for it as well. Slightly on topic, ModifyWorld is only for people not running MCPC+ servers, same thing for the PEX included with ForgePerms, its ment only for people not running MCPC+.

**Comment by Slind14** [comment]
So this means I get: 
- MyTown
- MyTownLib
- ForgePerms without PEX
- ForgePermsBridge for Bukkit (MCPC+)
- aPerf
- and Modifyworld for Bukkit

**Comment by jgoett154** [comment]
Don't forget Vault and a Bukkit perm plugin supported by Vault. Vault is used in ForgePermsCBBridge to access permissions, and chat prefixes if they work. Some people say they don't work.

**Comment by Slind14** [comment]
Chat Prefix works with MyTown-Chat, the only thing I miss is the playername. normaly you can color it by putting a color code at the end of the your prefix, this doesn´t work with mytown chat

**Comment by jgoett154** [comment]
I think when Alpha was coding it, he made it reset for chat. Either that or check the config, there may be a way to make it work. I am not looking at the code since im at school, but there may be a way to.

**Comment by jgoett154** [comment]
Off topic, but, did you make a channel for mytown already?

**Comment by Slind14** [comment]
you can join any not registered chat. you have to register an account in espernet and than register the channel. So it becomes yours and you can kick people ...

**Comment by jgoett154** [comment]
I joined #mytown and it says im not op. I also registered my nick with nickserv. I feel like a noob again :p

**Comment by Slind14** [comment]
you have to register the channel, too.

Can I use "1.5.1.1 - Without PEX" If I use Pex as bukkit permission plugin ?

**Comment by Slind14** [comment]
the first one who joins a not registered channel gets op, but as soon as you register it, it is urs.

**Comment by jgoett154** [comment]
Yes, you can use Bukkt PEX with ForgePerms.

I had registered my nick and then joined #mytown, and ran /chanserv register #mytown and it tells me im not OP. I really should have learned IRC better :p

**Comment by Slind14** [comment]
atm you are op and im not..

**Comment by jgoett154** [comment]
Ok, I registered the channel now. Thank you for OPing me

**Comment by Slind14** [comment]
np

**Comment by jgoett154** [comment]
Offtopic, but to answer your questions from IRC. I am in college, so im on my college campus at the moment. I didn't initially create it, someone named Alphaest did. I have been keeping it updated as best as I can while adding some features. I have no public server, I rely mostly on others to test it, I do however have an MCPC+ server I do some tests against that is on my desktop, but mostly when adding mod support or features.
