### ISSUE TITLE
1.6.1.11: Error in player EntityPlayerMP/NPE

### ISSUE THREAD

**Issue by CurePindal** [MyEssentials/MyTown#24]
Lots of spawn items produce "Error in player EntityPlayerMP"

To reproduce:
Use spawn egg.
Check log.

Server is running mcpc+ B110.

Log: http://pastebin.com/vhFaHguF

Anything else I can provide?

**Comment by jgoett154** [comment]
I used a few different vanilla spawn eggs and couldn't reproduce the error. I ran MCPC+ B110 and the latest MyTown, ForgePerms, etc without the error. What other mods are you using?

**Comment by CurePindal** [comment]
Quite a lot. http://pastebin.com/1tqqgE39

**Comment by jgoett154** [comment]
The only thing that is confusing me is the fact MyTown called the Thaumcraft 3 protection that is inside MyTown, but you have Thaumcraft 4 and it shouldn't have enabled it nor make a call to it.

**Comment by CurePindal** [comment]
Yep, found that pretty confusing too.
I cant pinpoint that issue, but if theres more info I can hand over please let me know.

**Comment by jgoett154** [comment]
Thaumcraft 4 protections have been added, and this should be fixed. Reopen if it still happens.
