### ISSUE TITLE
1.6.1.11: Command execution error

### ISSUE THREAD

**Issue by CurePindal** [MyEssentials/MyTown#26]
While testing the setup Ive issued "/town info test" and got this error. The town existed and when I tried the 2nd time it worked flawless. No clue why it bugged out.

Log: http://pastebin.com/GrJeLHh8

mcpc+ 1.6.4 b110

**Comment by jgoett154** [comment]
Fixed in the latest version. When getting prefix and suffix I had accidentally switched the arguments.
