### ISSUE TITLE
[Broken] The Item economy is broken in the latest version

### ISSUE THREAD

**Issue by Slind14** [MyEssentials/MyTown#28]
Hey,

the item economy is broken in the latest version. Claiming doesn´t cost anything atm. I´m back on an old version.

**Comment by jgoett154** [comment]
I will look into it, but make sure players don't have mytown.cost.bypass.townnew as that will bypass the cost for a new town.

**Comment by Slind14** [comment]
nah, we changed nothing, just updated.

**Comment by jgoett154** [comment]
Update to the latest version and in the ForgePermsCBBridge config, disable economy. That will ensure that ItemEcon is used.
