### ISSUE TITLE
Colored Name via Prefix

### ISSUE THREAD

**Issue by Slind14** [MyEssentials/MyTown#29]
Hey,

the Prefix works again in the current build, but the Name still doesn´t get the latest color code from the prefix.

**Comment by jgoett154** [comment]
Will be fixed in the next version :)

**Comment by jgoett154** [comment]
Latest version should have the name take the prefix color as well now

**Comment by Slind14** [comment]
its working now, thank you

**Comment by jgoett154** [comment]
No problem at all :)
