### ISSUE TITLE
1.5.2 source as repo?

### ISSUE THREAD

**Issue by Torins** [MyEssentials/MyTown#4]
Hey.

Would it be much work if I asked you to keep 1.5.2 sources as repositories on github?

**Comment by jgoett154** [comment]
I can upload a 1.5.2 only repo :)

**Comment by Torins** [comment]
As long as you plan to keep it updated :P Otherwise I'll just work it out from the 1.6.2 one

**Comment by jgoett154** [comment]
Lol, I do all development on 1.5.2 first, then just copy past to 1.6.2. The reason I do it that way is cause more modpacks are 1.5.2 right now so its a much higher priority :p

**Comment by jgoett154** [comment]
Here you go https://github.com/legobear154/MyTown-1.5.2 it has some extra protections I was working on, but just haven't released it officially yet :p still really need to figure out the grab feature of portalgun as well as gravitygun :(

**Comment by Torins** [comment]
Great thanks.
So what will be the order now? Ya commit to 1.5 and transfer to 1.6, commit to 1.6 and transfer to 1.5, or is this 1.5 repo a one time thing? :)

**Comment by jgoett154** [comment]
I will probably commit to 1.5 more than 1.6 but they will both be pretty much the same. Its safer that way anyways :p

**Comment by Torins** [comment]
Okay, thanks again.
