### ISSUE TITLE
MyTown Crashes with EE3

### ISSUE THREAD

**Issue by CoryManson** [MyEssentials/MyTown#48]
Morning Lego,

Getting the following crash when placing EE3 entities (Research table tested in this crash report)

Occurs inside and outside any town.

http://pastebin.com/Vi3sV3Ps

**Comment by CoryManson** [comment]
Found another log which may help too: http://pastebin.com/jDFq9p3u

**Comment by jgoett154** [comment]
Fixed: https://github.com/legobear154/MyTown/issues/52
