### ISSUE TITLE
I am too dumb to compile your mod

### ISSUE THREAD

**Issue by DJGummikuh** [MyEssentials/MyTown#5]
I have no clue what I'm doing wrong. I'm trying to compile your mod with the latest stable build from MCP and get compiler errors about what appears to be a call to an obfuscated method (func_b23155121 something, will post the exact error tomorrow morning).

Am I missing something obvious here?

**Comment by jgoett154** [comment]
Alpha had a few obfuscated functions like that, but I thought I had gotten rid of them all. Ill need the file and line of code to know for sure what is causing the issue. Also, are you using the ant build script I included? Its not the best build script in the world, but it does the job. Just make sure to change a few of the variables to fit your need.

**Comment by DJGummikuh** [comment]
Ok the problem was I didn't use your head commit but some 2 down below your "updated to 1.6" commit. 
With the head commit I could compile and (after a considerable amount of merging my own changes back in) am now running myTown on our 1.5.2 unleashed server properly. All that's missing is the new permissions adaption (were of course using permissionsEx up until now)

**Comment by Torins** [comment]
Hey. Glad to hear ya got the code to compile :)

For future reference though, this is the 1.6.2 branch.
If ya wish to grab 1.5.2 code, go over there: https://github.com/legobear154/MyTown-1.5.2

Legobear154 said he'll keep both branches up to date, at least for now

**Comment by DJGummikuh** [comment]
actually, I used your head commit, then changed the two or three locations in which the interfaces didn't match for 1.5... I am now running your 1.6 HEAD (plus my own changes) in 1.5
So far, I saw no side effects
