### ISSUE TITLE
Protection bypass: TE Florbs

### ISSUE THREAD

**Issue by tomelfring** [MyEssentials/MyTown#50]
Hello,

I've found out that you can bypass the protection of towns with Thermal Expension Florbs. You can place any kind of liquid in a town.

I'm running Mytown 1.6.1.16 on mcpc+

**Comment by odensc** [comment]
This is because the class names for TE are outdated. It is fixed in the dev branch, but that has not been release yet.

**Comment by jgoett154** [comment]
Should be fixed in next version.
