### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by Reddawg99** [MyEssentials/MyTown#6]
Hey, love the MyTown mod, but we are having a few issues with it.

First, I can't figure out how to set the default starting plot amount. It seems to be tied into permissions, but I can't find information on what node it is.

Second, we are having serious problems running MyTown on MCPC+ for 1.5.2. Is there a recommended MCPC version to use with the latest 1.5.2 build?

The problem we are having with MCPC+ is, soon as we add in MyTown, MCPC stops using PEX for permissions and defaults to SuperPerms. We HATE SuperPerms, we want PEX!

Any ideas? Thanks!

-Reddawg99

**Comment by jgoett154** [comment]
The amount is actually found in the config (ServerDirectory/config/MyTown/config.yml). I test with git-MCPC-Plus-jenkins-MCPC-Plus-Legacy-623 (MC: 1.5.2) Which doesn't seem to be available on jenkins anymore. PEX has support for SuperPerms built in, from my memory so it should still work.

Should add, make sure when using MyTown with MCPC+ that you also have ForgePerms in the mods folder, vault and ForgePermsCBBridge in the plugins folder, and ofc your preferred permission system too. Also, use ForgePerms without PEX included since it wont work with bukkit plugins.

**Comment by Reddawg99** [comment]
The config that generated didn't have anything for default plots, just nation plots.

**Comment by jgoett154** [comment]
There should be this in the config
S:TownClaimBlock=1x264

**Comment by Reddawg99** [comment]
AHA! It was hidden! Sneaky, sneaky. Thanks Lego, you can close this.

**Comment by Reddawg99** [comment]
Actually, wait. That would change the COST of claiming new plots, wouldn't it? I'm trying to change how many plots a new town starts with, and how many plots a town gets when it invites a player.

**Comment by jgoett154** [comment]
Oh, missread your question then :p whoops, sorry.

This may help:

How many plots a town has is defined by multiple things:
total blocks = perResidentBlocks + extraBlocks + nationBlocks.
perResidentBlocks = mayorMulti \* (for each res: + resMulti)
nationBlocks = nationAddsPerResident \* numResidents + nationAddsBlocks

mayorMulti is defined in PEX by mytown.mayor.blocks.(2|4|8|16|32) default 1
resMulti is defined in PEX by mytown.resident.blocksmulti.(2|4|8|10) default 1
extraBlocks can be set by the admin command /ta extra <town> <count>. It can be both positive and negative. Whatever the admin feels like doing to the town plot count.
nationAddsPerResident and nationAddsBlocks are defined in the config. Default is 0.

**Comment by Reddawg99** [comment]
Thats what I needed, thanks Lego!

I guess for now we will keep the server running Forge till we can make MCPC play nice.

**Comment by jgoett154** [comment]
MCPC+ should play nice, I test on MCPC+ and made ForgePerms and the bridge to help bridge the gap between the two.

**Comment by Reddawg99** [comment]
Is there a way to disable superperms, or bypass it? It keeps defaulting to it, no matter what.

**Comment by jgoett154** [comment]
What is your current setup? What I do is use MyTown and ForgePerms without PEX and toss those in the mods folder. Then I put ForgePermsCBBridge, Vault, and a Bukkit permission plugin (typically PEX) in the plugins folder. Then it should work.

Also, are you using my version from http://www.minecraftforum.net/topic/1889473-legobear154s-mods or Alpha's version?

**Comment by Reddawg99** [comment]
Yeah, we tried that exact setup. We could get onto the server fine, and /help even showed PEX was in there. However, no commands worked at all, even with a properly setup permissions file for PEX. Its just massive weirdness.

**Comment by jgoett154** [comment]
Hm, works fine on my end from what I have tried.

**Comment by Reddawg99** [comment]
I think what we will have to do is run a fresh copy of Unleashed with MCPC and nothing else, then add in the mods/plugins in the order you listed above, starting/stopping every now and then, and see if it works.

**Comment by Reddawg99** [comment]
Thanks for the help anyway, Lego. Been at this a few days already, hopefully we will have it running soon.

**Comment by jgoett154** [comment]
No problem, hopefully to work out the issue. I will look into it more and see if anything on my end is causing it.

**Comment by Reddawg99** [comment]
Try doing a build with the FTB unleashed server files and MCPC, it may be something in unleashed causing the weirdness.

**Comment by Torins** [comment]
@Reddawg99 When can you be online in IRC? I am currently on my way home and will be online in an hour or so. 
I want to take a look at your configuration and try to help. 

If you're interested, leave me a message here and catch me on esper.net, channel #mytown

**Comment by Reddawg99** [comment]
I actually don't use IRC. I'll be in our teamspeak at http://planetbeast.net/ working on the server tonight if you'd like to drop in.

**Comment by Torins** [comment]
Expect me to come online in an hour then :) can't promise I'll talk instead of writing though

**Comment by jgoett154** [comment]
First, since when did mytown have an irc channel? xD

Also, @Reddawg99, Just tested with FTB Ultimate, latest MCPC+, Vault, PEX, ForgePerms w/o PEX, MyTown (ofc), and Bukkit PEX and I gave myself ee.\* and mytown.\* and the commands worked for me. I can get on either IRC or the Teamspeak server so I can help figure out this issue :) And I second Torins, can't promise i'll talk but will write

**Comment by Reddawg99** [comment]
Jakimfett, our lead developer, figured out the MCPC issue thanks to your responses on the thread. Either of you are welcome to hop in tonight while we do further work on it. Might run into some issues you might be familiar with.

**Comment by jgoett154** [comment]
Ah ok, I wondered if he was talking about the same server as you :p anyways, glad everything is sorted out now.

**Comment by Torins** [comment]
Glad to hear it works. I'll still hop on for a short talk though if it won't be a problem. 

@legobear154
It doesn't (yet). But I'd rather make one and do support there than in channels I reside in :)

**Comment by Reddawg99** [comment]
Sorry I missed you guys, I was working on perms all night and TS didn't chime when I had a PM.

We do have it working, but once I switched mytown over to MySQL, the console gets a flood of reports any time a player uses a mytown perm. Weird.

**Comment by Reddawg99** [comment]
Ok, new issue guys. I'm getting things like this every time a player uses a mytown command in the console:

22.08 15:48:31 [Server] INFO [Bridge]XXX at Overworld requested mytown.chat.allowcaps
22.08 15:48:31 [Server] INFO [Bridge]XXX at Overworld requested mytown.chat.allowcolors

Any idea how to keep that from happening?

**Comment by Torins** [comment]
It's a debug line lego left in mytowncbbridge, thought it was removed by now though... 
I won't be near my PC with my modding env till tomorrow afternoon (morning us time), so ya  might wanna edit and recompile it yourselves.

**Comment by Reddawg99** [comment]
Solved, thanks Torin.
