### ISSUE TITLE
Withdrawing items without having one in your inventory withdraws but only receive 1

### ISSUE THREAD

**Issue by rjdunlap** [MyEssentials/MyTown#81]
Case 1 (correct):
Inventory 2 Dead Bushes
Bank Inventory 20 Dead Bushes
/town bank withdraw 5
Inventory 7 Dead Bushes
Bank Inventory 15 Dead Bushes

Case 2 (bug):
Inventory 0 Dead Bushes
Bank Inventory 20 Dead Bushes
/town bank withdraw 5
Inventory 1 Dead Bushes
Bank Inventory 15 Dead Bushes

Case 3 (bug):
Inventory 10 Dead Bushes
Bank Inventory 200 Dead Bushes
/town bank withdraw 100
Inventory 64 Dead Bushes
Bank Inventory 100 Dead Bushes

**Comment by rjdunlap** [comment]
MyTown2 0.2.0b
MyPermissions 1.7.10 - 28 dev
Core 1.13r

**Comment by krwminer** [comment]
This should have been in MyTown2... Anyway it is fixed in MyEssentials-Core-1.7.10-67-dev.jar.
